vim.cmd'hi!         Normal                              guifg=#ffffff   guibg=#1e1e1e   guisp=None'

vim.cmd'hi!         CursorLine                          guifg=None      guibg=#303030   guisp=None'

vim.cmd'hi!         ColorColumn                         guifg=None      guibg=#4d4d4d   guisp=None'

vim.cmd'hi!         WinSeparator                        guifg=#323232   guibg=#323232   guisp=None'
vim.cmd'hi!         StatusLine                          guifg=#999999   guibg=#323232   guisp=None'
vim.cmd'hi! link    StatusLineNC                        StatusLine'


vim.cmd'hi!         Keyword                             guifg=#ff7b72   guibg=None      guisp=None'
vim.cmd'hi! link    Conditional                         Keyword'
vim.cmd'hi!         Identifier                          guifg=#ffffff   guibg=None      guisp=None'
vim.cmd'hi! link    Operator                            Keyword'
vim.cmd'hi!         PreCondit                           guifg=#4eade5   guibg=None      guisp=None'
vim.cmd'hi!         Function                            guifg=#d2a8ff   guibg=None      guisp=None'
vim.cmd'hi! link    Exception                           Keyword'
vim.cmd'hi! link    Include                             Keyword'
vim.cmd'hi!         Type                                guifg=#fba557   guibg=None      guisp=None'
vim.cmd'hi!         Constant                            guifg=#79c0ff   guibg=None      guisp=None'
vim.cmd'hi! link    @function.macro                     Constant'
vim.cmd'hi!         String                              guifg=#a4d6fe   guibg=None      guisp=None'
vim.cmd'hi!         PreProc                             guifg=#4eace5   guibg=None      guisp=None'
vim.cmd'hi! link    Boolean                             Keyword'
vim.cmd'hi! link    Special                             bKeyword'
vim.cmd'hi!         Comment                             guifg=#808080   guibg=None      guisp=None'
vim.cmd'hi! link    Label                               Keyword'
vim.cmd'hi! link    Character                           String'
vim.cmd'hi!         Todo                                guifg=#a8c022   guibg=None      guisp=None'

vim.cmd'hi! link    Directory                           Type'
vim.cmd'hi! link    netrwClassify                       Keyword'
vim.cmd'hi!         Cursor                              guifg=None      guibg=#79c0ff   guisp=None'
vim.cmd'hi! link    lCursor                             Cursor'


vim.cmd'hi! link    @Colon                              Keyword'
vim.cmd'hi! link    @DoubleColon                        @Colon'
vim.cmd'hi! link    @Arrow                              Keyword'
vim.cmd'hi! link    @BigArrow                           @Arrow'
vim.cmd'hi! link    @GreaterThan                        Keyword'
vim.cmd'hi! link    @SmallerThan                        Keyword'
vim.cmd'hi! link    @lsp.type.enumMember                Identifier'
vim.cmd'hi!         @variable                           guifg=#fae3c6   guibg=None      guisp=None'
vim.cmd'hi! link    @variable.builtin                   @variable'
vim.cmd'hi! link    @type.builtin                       Type'
vim.cmd'hi! link    @variable.member                    Identifier'

vim.cmd'hi!         @lsp.mod.unsafe                     guifg=None      guibg=#4d3e3e   guisp=None'
vim.cmd'hi!         @lsp.typemod.keyword.unsafe         guifg=None  guibg=#1e1e1e   guisp=None'
vim.cmd'hi!         @lsp.typemod.function.declaration   guifg=None guibg=#1e1e1e guisp=None'
